version: "0.1"

services:
  mysqldb:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: idk
      MYSQL_DATABASE: idk
    ports:
      - 3306

  app:
    depends_on:
      - mysqldb
    build:
      dockerfile: Dockerfile_server
    command: bash -c '../misc/wait-for-it.sh mysqldb:3306 -- npm run dev'
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - 4000:4000
    environment:
      - PORT=4000

volumes:
  dbdata:
