version: "0.1"

services:
  mysqldb:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: idk
    ports:
      - 3306

  server:
    depends_on:
      - mysqldb
    build:
      dockerfile: Dockerfile_server
    command: bash -c '../misc/wait-for-it.sh mysqldb:3306 -- npm run dev'
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - PORT=${SERVER_PORT}
      - DB_HOST=mysqldb
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER=root
      - DB_PORT=3306

volumes:
  dbdata:
