version: "0.1"

services:
  app:
    build: .
    command: bash -c 'sleep 5; npm run start'
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - 4000:4000
    environment:
      - PORT=4000
